### ISSUE TITLE
Revert social media button at post footer to as it was! 

### ISSUE THREAD

**Issue by ranstigate** [ranstigate/ranstigate-blog#12]
Hi, 
This was not to be changed, it was ok in black the way it was. Why was this changed? 

I think this got changed when you fixed the floating icons bar..

Please revert to as it was.

![image](https://user-images.githubusercontent.com/56231190/66893826-99ac7200-f00c-11e9-9e66-6350e0eb532b.png)

**Comment by deysanjay74** [comment]
Done
