### ISSUE TITLE
Remove page footer grey box.

### ISSUE THREAD

**Issue by ranstigate** [ranstigate/ranstigate-blog#13]
Just leave the copy right and remove the icons and the grey box, make it all white like here: 

just keep copy symbol and name. remove the word "copyright"

© Ranstigate 2019

current: 
![image](https://user-images.githubusercontent.com/56231190/66897880-923d9680-f015-11e9-87b6-4a6ff368d34a.png)

eg:

![image](https://user-images.githubusercontent.com/56231190/66897689-20654d00-f015-11e9-8a64-82576dfb05fe.png)

**Comment by deysanjay74** [comment]
Removed
