### ISSUE TITLE
title share buttons not visible on mobile

### ISSUE THREAD

**Issue by ranstigate** [ranstigate/ranstigate-blog#3]
share buttons should show up here in the red box as shared in danielmiessler example. 

see eg: https://danielmiessler.com/blog/how-to-become-a-slack-ninja/

This was shared since day1

![image](https://user-images.githubusercontent.com/56231190/66273228-b2d85480-e88f-11e9-94e5-2bffb661a345.png)

**Comment by deysanjay74** [comment]
We already discussed.
