### ISSUE TITLE
Move the share buttons a little lower to center

### ISSUE THREAD

**Issue by ranstigate** [ranstigate/ranstigate-blog#4]
right now its at the very top of the page. 

![image](https://user-images.githubusercontent.com/56231190/66272849-37c16f00-e88c-11e9-84da-e75510add61b.png)

![image](https://user-images.githubusercontent.com/56231190/66273149-0302e700-e88f-11e9-88e5-e0bfd833846d.png)

**Comment by deysanjay74** [comment]
Done. please check and confirm
